#
# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Charleye <wangkart@aliyun.com>
#

obj-$(CONFIG_$(SPL_)BOOT_DEVICE) += bootdevice-uclass.o
obj-$(CONFIG_$(SPL_)BOOT_DEVICE_GPIO) += bootdevice-gpio.o
obj-$(CONFIG_$(SPL_)BOOT_DEVICE_SYSCON) += bootdevice-syscon.o
