#
# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Charleye <wangkart@aliyun.com>
#

obj-$(CONFIG_DM_BOOT_DEVICE) += bootdevice-uclass.o
obj-$(CONFIG_DM_BOOT_DEVICE_GPIO) += bootdevice-gpio.o
