# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Charleye <wangkart@aliyun.com>
#
#

obj-$(CONFIG_TARGET_LMT_FPGA) += lambert/
obj-$(CONFIG_TARGET_LUA_FPGA) += laguna/
obj-$(CONFIG_TARGET_LUA_R5F_FPGA) += laguna_r5f/
