# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2022 Horizon Robotics Co,.Ltd.

obj-y	+= lowlevel_init.o
obj-y	+= board.o

ifdef CONFIG_HOBOT_J6P
obj-y	+= j6.o
endif

ifdef CONFIG_HOBOT_J6E
obj-y	+= j6e.o
endif
