# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Charleye <wangkart@aliyun.com>
#

obj-$(CONFIG_$(SPL_TPL_)CLK_AXERA) += clk-mux.o clk-gate.o
obj-$(CONFIG_$(SPL_TPL_)CLK_AXERA) += clk-divider.o clk-pll.o
obj-$(CONFIG_$(SPL_TPL_)CLK_AXERA) += clk-tree.o pll-ctrl.o
