# SPDX-License-Identifier: GPL-2.0+

obj-$(CONFIG_$(SPL_)DM_GLBCON) += glbcon.o
obj-$(CONFIG_$(SPL_)FDL) += fdl/
obj-$(CONFIG_$(SPL_)FDL_USB_DRV) += usb/
obj-$(CONFIG_$(SPL_TPL_)ABORT_ALARM) += abort-alarm.o
