#ifndef ASM_LAGUNA_BOOTPARAM_H_
#define ASM_LAGUNA_BOOTPARAM_H_

typedef struct boot_params {
	void *fdt_addr;
	unsigned short bootdevice;
} boot_params_t;


static inline boot_params_t *boot_params_get_base(void)
{
	/* TODO: detect base during runtime */
	return (boot_params_t *)CONFIG_LUA_IRAM_BASE;
}

enum {
	BOOTDEVICE_ONLY_EMMC = 0x1,
	/* Main OSPI interface */
	BOOTDEVICE_ONLY_NOR,
	BOOTDEVICE_ONLY_NAND,
	BOOTDEVICE_ONLY_HYPER,

	/* Safety QSPI + Main OSPI interface */
	BOOTDEIVCE_BOTH_NOR_NOR,
	BOOTDEVICE_BOTH_NOR_NAND,
	BOOTDEVICE_BOTH_NOR_HYPER,
	BOOTDEVICE_BOTH_NAND_NOR,
	BOOTDEVICE_BOTH_NAND_NAND,
	BOOTDEVICE_BOTH_NAND_HYPER,
	BOOTDEVICE_BOTH_HYPER_NOR,
	BOOTDEVICE_BOTH_HYPER_NAND,
	BOOTDEVICE_BOTH_HYPER_HYPER,

	/* Safety QSPI + Main SDHCI interface */
	BOOTDEVICE_BOTH_NOR_EMMC,
	BOOTDEVICE_BOTH_NAND_EMMC,
	BOOTDEVICE_BOTH_HYPER_EMMC,

	/* Special interface */
	BOOTDEVICE_UART,
	BOOTDEVICE_USB,
	BOOTDEVICE_SD,
};

enum {
	BOOTMODE_DOWNLOAD,
	BOOTMODE_BOOTUP,
};

enum {
	DOWNLOAD_IF_UART,
	DOWNLOAD_IF_USB,
	DOWNLOAD_IF_CAN,
	DOWNLOAD_IF_SD,
};

#endif /* ASM_LAGUNA_BOOTPARAM_H_ */