# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2024 Charleye <wangkart@aliyun.com>
#
#

obj-$(CONFIG_AXERA_LMT) += lambert/
obj-$(CONFIG_AXERA_LUA) += laguna/
obj-$(CONFIG_ARCH_AXERA_R5F) += laguna_r5f/
